# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('projectRcn', models.PositiveIntegerField()),
                ('projectAcronym', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('shortName', models.CharField(max_length=100)),
                ('activityType', models.CharField(max_length=100)),
                ('endOfParticipation', models.BooleanField()),
                ('ecContribution', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=20)),
                ('organizationUrl', models.URLField()),
                ('contactType', models.CharField(max_length=100)),
                ('contactTitle', models.CharField(max_length=5)),
                ('contactFirstNames', models.CharField(max_length=100)),
                ('contactLastNames', models.CharField(max_length=100)),
                ('contactFunction', models.CharField(max_length=100)),
                ('contactTelephoneNumber', models.CharField(max_length=100)),
                ('contactFaxNumber', models.CharField(max_length=100)),
                ('contactEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('rcn', models.PositiveIntegerField()),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('topics', models.CharField(max_length=100)),
                ('frameworkProgramme', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('projectUrl', models.URLField()),
                ('objective', models.CharField(max_length=3000)),
                ('totalCost', models.FloatField()),
                ('ecMaxContribution', models.FloatField()),
                ('call', models.CharField(max_length=100)),
                ('fundingScheme', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=250)),
                ('coordinatorCountry', models.CharField(max_length=2)),
                ('participants', models.CharField(max_length=250)),
                ('participantCountries', models.CharField(max_length=250)),
                ('subjects', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Project'),
        ),
    ]
