# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organizationID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('shortName', models.CharField(max_length=100)),
                ('activityType', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=2)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('postCode', models.CharField(blank=True, max_length=7, null=True)),
                ('organizationUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('topics', models.CharField(max_length=100)),
                ('frameworkProgramme', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=250)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('projectUrl', models.URLField(blank=True, null=True)),
                ('objective', models.CharField(max_length=3000)),
                ('totalCost', models.FloatField()),
                ('call', models.CharField(max_length=100)),
                ('fundingScheme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=15)),
                ('endOfParticipation', models.BooleanField()),
                ('ecContribution', models.FloatField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('order', models.IntegerField()),
                ('level', models.IntegerField()),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('nutsCode', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Region')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='regionCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Region'),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Project'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Project'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectorganisation',
            unique_together=set([('project', 'organisation')]),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set([('user', 'project')]),
        ),
    ]
