# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataTool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='totalCost',
            field=models.CharField(max_length=12),
        ),
    ]
