# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataTool', '0003_auto_20170427_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.CharField(max_length=10),
        ),
    ]
