# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataTool', '0003_auto_20170619_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(max_length=50000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Project')),
            ],
        ),
    ]
