# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataTool', '0004_projecttopics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttopics',
            name='json',
        ),
        migrations.AddField(
            model_name='projecttopics',
            name='confidenceLevel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttopics',
            name='importance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttopics',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttopics',
            name='relevance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttopics',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttopics',
            name='typeGroup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
