# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataTool', '0005_auto_20170621_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField(default=0)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Industry')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Project')),
            ],
        ),
    ]
