# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataTool', '0005_auto_20170427_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisation',
            new_name='Organisations',
        ),
    ]
