# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataTool', '0006_industry_projectindustry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
