# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataTool', '0006_auto_20170427_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('projectRcn', models.IntegerField()),
                ('projectAcronym', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('shortName', models.CharField(max_length=100)),
                ('activityType', models.CharField(max_length=100)),
                ('endOfParticipation', models.BooleanField()),
                ('ecContribution', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=20)),
                ('organizationUrl', models.URLField()),
                ('contactType', models.CharField(max_length=100)),
                ('contactTitle', models.CharField(max_length=5)),
                ('contactFirstNames', models.CharField(max_length=100)),
                ('contactLastNames', models.CharField(max_length=100)),
                ('contactFunction', models.CharField(max_length=100)),
                ('contactTelephoneNumber', models.CharField(max_length=100)),
                ('contactFaxNumber', models.CharField(max_length=100)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenDataTool.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='organisations',
            name='projectID',
        ),
        migrations.DeleteModel(
            name='Organisations',
        ),
    ]
