# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataTool', '0007_auto_20170427_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='ecContribution',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='projectRcn',
            field=models.PositiveIntegerField(),
        ),
    ]
