from django.db import models


class Project(models.Model):
    rcn = models.PositiveIntegerField()
    id = models.CharField(max_length=20, primary_key=True)
    acronym = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    programme = models.CharField(max_length=100)
    topics = models.CharField(max_length=100)
    frameworkProgramme = models.CharField(max_length=100)
    title = models.CharField(max_length=250)
    startDate = models.CharField(max_length=10)
    endDate = models.CharField(max_length=10)
    projectUrl = models.URLField()
    objective = models.CharField(max_length=3000)
    totalCost = models.CharField(max_length=12)
    ecMaxContribution = models.CharField(max_length=12)
    call = models.CharField(max_length=100)
    fundingScheme = models.CharField(max_length=100)
    coordinator = models.CharField(max_length=250)
    coordinatorCountry = models.CharField(max_length=2)
    participants = models.CharField(max_length=250)
    participantCountries = models.CharField(max_length=250)
    subjects = models.CharField(max_length=250)


class Organisation(models.Model):
    projectRcn = models.PositiveIntegerField()
    projectID = models.ForeignKey(Project)
    projectAcronym = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    id = models.CharField(max_length=20, primary_key=True)
    name = models.CharField(max_length=250)
    shortName = models.CharField(max_length=100)
    activityType = models.CharField(max_length=100)
    endOfParticipation = models.BooleanField()
    ecContribution = models.CharField(max_length=12)
    country = models.CharField(max_length=100)
    street = models.CharField(max_length=250)
    city = models.CharField(max_length=100)
    postCode = models.CharField(max_length=20)
    organizationUrl = models.URLField()
    contactType = models.CharField(max_length=100)
    contactTitle = models.CharField(max_length=5)
    contactFirstNames = models.CharField(max_length=100)
    contactLastNames = models.CharField(max_length=100)
    contactFunction = models.CharField(max_length=100)
    contactTelephoneNumber = models.CharField(max_length=100)
    contactFaxNumber = models.CharField(max_length=100)
    contactEmail = models.EmailField()
